name: Build TWRP 14.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v8
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'false'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git repo python3 bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32z1-dev libelf-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev

      - name: Initialize Repo
        run: |
          mkdir -p ~/bin
          PATH=~/bin:$PATH
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          mkdir twrp
          cd twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1 --depth=1
          repo sync -j8 --no-clone-bundle --no-tags --optimized-fetch

      - name: Setup Device Tree & Configure Lunch
        run: |
          cd twrp
          mkdir -p device/ant/b2_ultra
          git clone https://github.com/superminyon/twrp_android_device_iiif150_b2_ultra.git device/ant/b2_ultra --depth=1
          
          # Eski ve geçersiz vendorsetup.sh dosyasını kaldırıyoruz
          rm -f device/ant/b2_ultra/vendorsetup.sh
          
          # Android 14 derleme sisteminin istediği doğru formata göre AndroidProducts.mk güncelleniyor
          echo "" >> device/ant/b2_ultra/AndroidProducts.mk
          echo "COMMON_LUNCH_CHOICES := omni_B2_Ultra-eng omni_B2_Ultra-userdebug" >> device/ant/b2_ultra/AndroidProducts.mk

      - name: Start Building
        run: |
          cd twrp
          . build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_B2_Ultra-eng
          mka recoveryimage
